services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - .:/workspace
    depends_on:
      - db
    tty: true
  db:
    image: mysql:8.0
    ports:
      - "5432:5432"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db:/var/lib/mysql

volumes:
  db:
